plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'br.com.compartilharprojetos.app'
    compileSdk 35

    defaultConfig {
        applicationId "br.com.compartilharprojetos.app"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.activity:activity:1.8.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'com.google.android.play:review:2.0.1'

    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.biometric:biometric:1.1.0'
    implementation 'androidx.webkit:webkit:1.9.0'

    implementation platform('com.google.firebase:firebase-bom:33.2.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'

    implementation 'com.google.android.play:app-update:2.1.0'
}