name: Compilar APK Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # ISSO CRIA O BOTÃO PARA COMPILAR O APK MANUALMENTE

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v5 # Atualizado para v5 para remover o aviso de depreciação
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar o APK
      # Removido o 'cd' - o robô vai rodar direto na raiz onde está o gradlew
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Disponibilizar APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: CompartilharProjetos-APK
        # Caminho corrigido, indo direto na pasta app
        path: app/build/outputs/apk/release/app-release.apk
